import fetchQL from "./fetchQL";
import styles from "./page.module.css";
import Link from "next/link";
// import Image from 'next/image'

async function getData(article) {
  const res = await fetchQL(article);
  // The return value is *not* serialized
  // You can return Date, Map, Set, etc.

  // Recommendation: handle errors
  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

// export const metadata = {
//   title: 'Disney Articles',
//   // description: 'Generated by create next app',
// }

// export async function generateMetadata({ params, searchParams }) {
export async function generateMetadata({ params }) {
  return { title: `Disney Articles - ${params.article}` };
}

export default async function Article({ params }) {
  const data = await getData(params.article);

  console.log(data?.data?.characters?.items[0].name);
  const nextPage = Number(params?.article) + 1;

  return (
    <main className={styles.main}>
      <section className={styles.content}>
        <h1>Article – {params.article}</h1>
        <Link href={`/articles/${nextPage}`}>Next Page</Link>
        {data?.data?.characters?.items.map(
          ({ _id, name, imageUrl, films, shortFilms, tvShows, videoGames }) => {
            return (
              <div key={_id}>
                <div className={styles.block}>
                  <h2>{name}</h2>
                  <img src={imageUrl} alt={name} width={400} height={400} />
                  <p>
                    shortFilms: <b>{shortFilms}</b>
                  </p>
                  <p>
                    tvShows: <b>{tvShows}</b>
                  </p>
                  <p>
                    videoGames: <b>{videoGames}</b>
                  </p>
                  <p>
                    films: <b>{films}</b>
                  </p>
                </div>
              </div>
            );
          }
        )}
      </section>
    </main>
  );
}
